name: Query Issues Output
on:
  workflow_dispatch:
#  schedule:
#  - cron: "0 0 * * *"

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
    - uses: christothes/IssueOutputAction@v1.1
      id: upload
      with:
        repotoken: ${{ secrets.GITHUB_TOKEN }}
        searchquery: 'is:open'
        repoOwnerAndName: 'rsymo-org/Query-Issues-Output-test' 

    - uses: actions/download-artifact@v3
      id: download
      with:
        name: issueoutput_${{ github.run_id }}
        path: ${{ steps.upload.outputs.issuesDirPath }}

#    - name: 'Echo download path and take a look at files on the filesystem'
#      run: echo ${{ steps.download.outputs.download-path }}
#      run: ls -la; cd issues; ls -la 

    - name: Zip the issue JSON files
      run: zip -r issues.zip ./issues

    - uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.MAIL_USERNAME }}
        password: ${{ secrets.MAIL_PASSWORD }}
        subject: Github Issue Query with JSON attached
        to: rsymo@github.com
        from: GitHub Actions # <user@example.com>
        body: "The issues that match the query are attached!"
        # Optional attachments: Send out the zipped up files
        attachments: issues.zip
        # Optional attachments: Send out the JSON files all attached to the email
        #attachments: ./issues/*.json
